### ISSUE TITLE
[Feature Request] Navigational Links

### ISSUE THREAD

**Issue by bassforce86** [ChristopherKlay/StadiaEnhanced#1]
Great work on this. 

There's a small improvement here to change the navigational links to relative links. Certainly for people who use multiple accounts for Stadia, the ability to maintain `https://stadia.google.com` **/u/{id}** `/rest_of_link` is really important, otherwise you're logged out of Stadia every time you link on the "Pro" link (for example).

using `window.open('/store/list/2001')` would probably solve it.

**Comment by ChristopherKlay** [comment]
I adjusted the URL's to i.e. `window.open("/store/list/2001", "_self");` for "Pro", as well as captures, achievements and such.

I'm currently only using one account, so i have to wait till later to actually check if that fixes the issue, since using the default (u/0/ with one account only) gets hidden when you change pages and i can't make sure that's actually included when using multiple accounts. If someone could drop the code above in a console with multiple accounts logged in and check if you stay on the same account, that would also be helpful. (:

I'm currently waiting for day-one issues to pop up, will fix those over the day and then drop a patch afterwards that should fix all of those (:
