### ISSUE TITLE
Wishlist filter not fully working?

### ISSUE THREAD

**Issue by superm1991** [ChristopherKlay/StadiaEnhanced#101]
Hello Christopher, and thanks a lot for the wishlist system!

I have added some games/bundles into the wishlist ... but some of them do not appear when the Wishlist filter is active.

Examples KO:
- "HITMAN 3 - Standard Edition" [bundle] is on my whishlist (full heart in the HM3 store page) but it **does not appear** with Wishlist filter on "All games" store page
- "Windbound" [game] is on my whishlist (full heart in the WB store page) but it **does not appear** with Wishlist filter on "All games" store page

Examples OK:
- "The Elder Scrolls Online: Standard Edition" [bundle] is on my whishlist (full heart in the ESO store page) and appears with Wishlist filter on "All games" store page
- "Assassin's Creed Valhalla" [game] is on my whishlist (full heart in the ACV store page) and appears with Wishlist filter on "All games" store page

I can't quite understand what went wrong...

Is there a way to display some kind of behind-the-scenes status of the list?

**Comment by ChristopherKlay** [comment]
I think i've found the issue. When getting the SKU's, i expected them to be 32 chars long. For some reason, some entries do have a "p" added onto the end of the SKU however, which results in them not displaying correctly.

The Watch_Dogs Complete Edition for example has the SKU of `57147ceff15149a09b17978a3cb5f043p`, despite the "p" not doing anything. In fact, there isn't even an article listing with the same SKU but without the "p".

Since i'm not entirely sure what the "p" marker does so far, i won't include it in the SKU that's saved in the wishlist. I will in return just check if a store entry includes the wishlisted SKU (as in; "541" will also show "541p") so your current wishlist keeps working fine and displays the games/dlc correctly after the patch later today.

> Is there a way to display some kind of behind-the-scenes status of the list?

Yes, for all Stadia Enhanced settings actually.

Any kind of saved data by the extension can be viewed via;

1. Visit the Stadia website
2. Ctrl+Shift+I
3. Go to the "Application" tab at the top
4. Select "Local Storage" on the left
5. Click "http://stadia.google.com

The entry with the SKU's for wishlisted items for example would be `enhanced_wishlist`

**Comment by ChristopherKlay** [comment]
Should be fixed with `v1.9.1` (:

**Comment by superm1991** [comment]
Looks good!
Thanks! :)
