### ISSUE TITLE
Unable to play in 1440p

### ISSUE THREAD

**Issue by PexBit** [ChristopherKlay/StadiaEnhanced#109]
Since today the stream defaults to 1080p after selecting 1440p. 4k works though. Tried other browsers/machines to no avail. Even tried another stadia extension (Stadia+) which I previously used and it doesn't work as well. My guess is Google changed something on their end.

**Comment by ChristopherKlay** [comment]
Thank you for informing me - it's true.

Google changed the codec detection on chrome to also use a detection based on supported media capabilities, which can revert VP9 to H264 and thus blocking 1440p/2160p in some cases, since those are limited to VP9.

I already added a fix to the new version of Stadia Enhanced (`v1.10.0`) that will overwrite the process and re-enables being able to freely chose your codec and resolution. 1440p will be fully available again as well.

I originally planned to release this update a bit later (due to still working on other aspects of the extension), but seeing that these changes from Googles side once again can easily cause people to be unable to play on their devices, i will push the update out this night (it's 3am here). It will go live here on GitHub and into verification on the Chrome Store in less than an hour.

**Comment by PexBit** [comment]
Thank you for your quick fix. I

> which can revert VP9 to H264 and thus blocking 1440p/2160p in some cases, since those are limited to VP9

This didn't seem to be the case. VP9 was always enabled while it defaulted back to 1080p - I've specifically checked this to rule out local codec issues.

I also tested v1.10.0 and it works, but the stream stays 1080p for 1 - 2 minutes until ist switches to chosen resolution. This might lead to some people thinking that it still doesn't work. It's not game specific on my end.

Again, thanks for your quick work. Without your extention, stadia would be useless to a lot of people, since Google is assuming everyone using stadia either has a small screen or 4k home cinema at home /irony.

**Comment by ChristopherKlay** [comment]
> This didn't seem to be the case. VP9 was always enabled while it defaulted back to 1080p - I've specifically checked this to rule out local codec issues.

This was mostly based on what codec Google new check picked as the default, which wasn't always correct by far.

In my case for example, the newly picked default was Hardware H264 decoding - despite the test setup only supporting H264 at 30fps. The performance basically went to unplayable entirely, while VP9 would've worked perfectly fine.

Resolution switching is definitely something i will keep an eye on.
