### ISSUE TITLE
Typos in German language ressources

### ISSUE THREAD

**Issue by Breeki32** [ChristopherKlay/StadiaEnhanced#132]
There are several typos for the German part. I've provided a PR with fixes (the way this is usually done on GitHub). Enjoy.

**Comment by ChristopherKlay** [comment]
The "way it's usually done on GitHub" would be to read the [readme file](https://github.com/ChristopherKlay/StadiaEnhanced#pull-requests) first, which highlights;

> **The main point about this repository is to provide the sourcecode of the current release version of Stadia Enhanced**. Pull requests for new feature implementations will be manually merged into the (non-public) dev version and tested for errors, before being released with the next public version of the extension. **Please post updates to translations in their respective discussions.** No content will be pulled directly into the current release version.

I've made an exception here and pulled the request in, since i updated to a new version shortly after and the new files correctly represent the new version of the extension. I'm glad someone highlighted those errors and they are fixed in the new version that just went into verification on the Chrome Store as well; but next time please post these in the actual topics for their language. It drastically helps organizing any changes between patches (and opens them up to discussions), especially for community members working on them, who might not be as experienced with GitHub.

Please note that this repository isn't a live/working repository. It's a storage for the source code of the currently live version of the extension only, that functions as a hub for bug reports, feature request and translations. It's a project build with the community - but the actual development isn't shared/public.

**Comment by Breeki32** [comment]
> Please note that this repository isn't a live/working repository. 

Sorry, I misinterpreted this project as "Open Source", that way updates via PR would work.
