### ISSUE TITLE
[Minor Issue] Search Button requires hitting Enter key, click doesn't work.

### ISSUE THREAD

**Issue by Phase10-5828** [ChristopherKlay/StadiaEnhanced#140]
As per the title, I can't click the search button and start typing, I have to click it then hit the enter key, its mildly annoying!
Brave v1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)
Revision -- 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}

Also tested in Regular Chrome v91.0.4472.114

Only does this with Stadia Enhanced enabled (with and without other extensions)

**Comment by ChristopherKlay** [comment]
Thanks for reporting the issue!

The function that auto-hides the Stadia Enhanced menu if you click outside of it, caused the search function to disappear again when clicked on smaller screens, due to triggering a action outside of it (hiding the menu).

I already fixed it in the dev build and it will go live with `1.14.0` soon. Might drop tomorrow already (:
