### ISSUE TITLE
Wishlist not working anymore?

### ISSUE THREAD

**Issue by superm1991** [ChristopherKlay/StadiaEnhanced#154]
Hi,

All my settings have been reset (and that's okay) so I tried adding back some stuff into the wishlist... but it doesn't seem to work: the wishlist filter continues to show all games regardless of wishlist contents.

**Comment by ChristopherKlay** [comment]
Thanks for pointing this out.

The wishlist was trying to load a old settings variable and thus didn't correctly. I also noticed another issue where some games don't show the red heart icon correctly when a game is in the wishlist, because the games ID got added incorrectly.

`1.16.2` just went into verification and should fix both issues. (:
