### ISSUE TITLE
Streched game icons?

### ISSUE THREAD

**Issue by aparadis** [ChristopherKlay/StadiaEnhanced#17]
Running v1.5.1 on Chrome 85 (Windows 10)

Seems since not too long ago, my game icons size are all stretched when using grid sizes 2-5. 

See here as an example:

- Grid size 2: https://imgur.com/a/i5AGyCb   
- Grid Size 3: https://imgur.com/a/XAAt9xy

Let me know if you need any other information.   Thanks and great work on the extension ;)

**Comment by Gromulan** [comment]
I am now experiencing the same issue. It seemed to coincide with me playing with the VP9/H264 options.

I now have 12 icons across and playing with grid size only changes the graphic zoom inside the tiles.

Only occurring on the HOME tab

Uninstalling and reinstalling the plugin did not correct

SHIFT F5 did not correct

![plugin glitch](https://user-images.githubusercontent.com/34243275/95648249-be161f80-0aa3-11eb-8707-2a6456c103dc.jpg)

**Comment by ChristopherKlay** [comment]
This issue came up, because Google changed how the homescreen is displayed on their end. They changed the game icons from a fixed size (that Enhanced was using to calculate the smaller tiles) to a different approach that scales them based on a ratio and related to their parent element.

I'm aware of the issue and already working on a hotfix that will be pushed later today.

At least it kinda looks like Google is going to implement different layouts/sizes at this point, which is a good thing.

**Comment by ChristopherKlay** [comment]
It's working again now with the v1.5.2 hotfix that just updated the project page here and got send into verification to Google. (:

![Stadia Homescreen](https://i.imgur.com/4LKnCiw.png)
