### ISSUE TITLE
Filters are gone?

### ISSUE THREAD

**Issue by superm1991** [ChristopherKlay/StadiaEnhanced#190]
I don't see filter options in store pages anymore...

**Comment by ChristopherKlay** [comment]
Yea, Stadia made changes to the store (and lots of other parts).

Will push out a hotfix later today (:

**Comment by ChristopherKlay** [comment]
A little update:

The changes are sadly bigger than i hoped and i had to make some drastic changes to how store elements are filtered out, because the actual store entry doesn't contain any informations about the type of entry (i.e. game, bundle, addon) anymore, outside of the actual text on the UI element. They also removed the game/store ID from those entries entirely.

The hotfix will restore the filter for games, bundles and addons (by using language based filtering, similar to the letterbox filter in the library), but the wishlist function is going to be deactivated for now, at least until i can find another way to make it work - or Stadia hopefully provides their own solution.

**Comment by superm1991** [comment]
Oh wow, that's bad news!
But thanks for the update!

**Comment by ChristopherKlay** [comment]
![image](https://user-images.githubusercontent.com/12472611/139595786-4c3fdc8d-3d55-4e76-80e0-788e9e04dea0.png)
Filters are already working again in the dev build, wishlisting is - as far as i can tell - currently not possible anymore, however.

Previously, games included the type of entry in their attributes, i.e. `17:3`, so filtering them via specific CSS rules was possible, but those attributes have been removed. I went ahead and gathered the actual text strings used by Stadia for the currently supported languages and implemented a filtering process based on those, which runs fine - but has to be manually updated. If the filter options aren't showing up in a specific (Stadia-supported) language in the future, adding them is quick and easy as well.

Wishlisting however, was based on store entries also featuring the given ID of each specific store entry (so games and their deluxe versions had different ID's, for example). Those infos have been replaced with action triggers that load the store page, without the ID being accessible from the DOM element anymore. The hotfix will hide the wishlisting functionality for now, until i find a way to implement it again - any wishlists saved in user profiles will be kept for the future.

**Comment by ChristopherKlay** [comment]
`1.17.6` just went into verification and should fix the store filtering.

Let me know if it works (:

**Comment by superm1991** [comment]
Yes, it's working fine with 1.17.6 (my Stadia account is in English).
Thanks again!

(And I hope we get a solution for the wishlist at some point :) )

**Comment by ChristopherKlay** [comment]
I tested a few other languages as well and everything should work.

We'll see about wishlisting. I'll implement when i can, but i hope Stadia does it first :p
