### ISSUE TITLE
Latest release (1.18.0) wants to read my browsing history

### ISSUE THREAD

**Issue by sukahiroaki** [ChristopherKlay/StadiaEnhanced#193]
![extension](https://user-images.githubusercontent.com/1401478/142626716-64229203-0719-4852-b8ac-2de4ff45fd0c.jpg)

Thankfully Chrome has blocked this. As I didn't see any mention in the Changelog, my question is: Why? Is this an error?

**Comment by ELowry** [comment]
Here's a quote from @ChristopherKlay on the [update's Reddit post](https://www.reddit.com/r/Stadia/comments/qxehx9/stadia_enhanced_version_118_changelog_infos/):

> The extension will request access to your "browser history" once more (this was already the case), due to changing on which pages the extension actually loads. It won't load on pages that don't need the extension (i.e. the couch page), or if no user is logged in to begin with - previously it simply loaded on any website on Stadias domain. Your actual "browser history" is not being accessed, the permission is simply needed to check the current URL you are on, to gather for example the ID of the current game.

**Comment by amcduffee** [comment]
I think the above information should be clearly stated on this repository now too.  The extension page, in the Chrome Store, only provides links to this repository and not everyone will think to look at the issues tab to find this information.

**Comment by ChristopherKlay** [comment]
Thank you for quoting me here, @ELowry.

The permissions aren't new, Chrome simply has to request them again because i changed how the extension filters pages to actually run on. Before the changes, the extension was running based on this:
```
"matches": ["*://stadia.google.com/*"],
"exclude_matches": ["*://stadia.google.com/capture/*", "*://stadia.google.com/families", "*://stadia.google.com/games", "*://stadia.google.com/couch", "*://stadia.google.com/tv"]
```
and the more Stadia grows, the longer the list of pages to exclude would be, with each new page potentially breaking something if the extension loads incorrectly. Version `1.18.0` changed this to use:
```
"matches": ["https://stadia.google.com/u/*", "*://stadia.google.com/home*", "*://stadia.google.com/store*", "*://stadia.google.com/player*", "*://stadia.google.com/explore*", "*://stadia.google.com/profile*", "*://stadia.google.com/settings*"]
```
which effectively means the extension only runs on pages it actually needs to run on, including pages with multiple logged in users (the `/u/*` part).

Due to the use of wildcards (the `*` in these paths), the permission for the browser history is triggered, since it's required to access the current URL of the website as well. **This doesn't mean the extension will ever read your actual browser history.**

I will update the readme with a permissions list together with a hotfix later today (:

**Comment by ChristopherKlay** [comment]
Update: Added details/explanation to [the readme](https://github.com/ChristopherKlay/StadiaEnhanced#permissions).
