### ISSUE TITLE
Store pages partial loading vs. filters

### ISSUE THREAD

**Issue by superm1991** [ChristopherKlay/StadiaEnhanced#198]
Hi,

Store pages (like https://stadia.google.com/store/list/3 ) load in "steps" of 50 items:
- when you open the page, it loads the first "step" (50 items) which goes from [A Place for the Unwilling] to [Destiny 2: Legendary Edition]
- when you scroll down, it loads the second "step" (50 items) which goes from [Destiny 2: The Witch Queen] to [From Space - Multiplayer Demo]
- etc...

**Bug:** Apparently, filters are only applied to the first step...
If I filter for "Games only", I get:
- only 33 items in the first step, but it still goes from [A Place for the Unwilling] to [Destiny 2]
- 50 items in the second step (the exact same items as without filter, it contains Games AND Bundles), from [Destiny 2: The Witch Queen] to [From Space - Multiplayer Demo]

**Comment by ChristopherKlay** [comment]
Thanks for reporting the issue!

Google apparently changed a few things around the store and one of those changes (a fairly weird one, to be honest) is that while store entries get loaded in a list, new entries after the first 50 get loaded into a new list, into one of those list entries, instead of just being added to the main list. It works more like adding a folder into a list, for some reason.

I can't fully "fix" this, so i decided to actually style the different "chunks" that load (Google by default just leaves a bigger margin between those areas) and re-wrote how the store filters work to check for all possible items in any available list of the current page. It isn't perfect and there can be gaps (since a new "chunk" has to start in a new line), but works and looks fairly decent still.

In the next patch, the worst-case scenario will be gaps like this (you can also see the thin line showing a new "chunk" has been loaded):
![image](https://user-images.githubusercontent.com/12472611/142978174-3c4ddb38-70a8-4749-9ff3-7711c93a303b.png)

Everything else should work again (:
