### ISSUE TITLE
[Feature Request] Chat improvements

### ISSUE THREAD

**Issue by Lordubuntu94** [ChristopherKlay/StadiaEnhanced#21]
Specifically i was thinking about 2 things:

1)  I do not like the message preview ( with also the date displayed on top-right) that we have into the friend list, and more than that i find it redundant since we have (near the friend list) a dedicated messages section. I think we may improve this adding to the other filters, one that  let the users chose if they want to hide the message preview or not.

2) As far as i like the fact that finally we have a chat system, unfortunately it's very basic. So at least, to a certain degree, it may be cool to have an emoji integration. I was testing this with some friends of mine, if you copy some emoji from for example, https://emojipedia.org/ the stadia chat was actually able to display it. Maybe we can add an emoji button near the textfield into the chat, so we can have a better messagging experience.

**Comment by ChristopherKlay** [comment]
Finally got access to messaging (without changing languages) now as well, so i can actually work on these things and test different languages before submitting changes.

The emoji button sounds great as a popup and shouldn't be too hard to implement.

The message preview is definitely doable, due to the nature of the friend list / messaging menu mix i'm not really sure where to add the toggle/option for that yet however. Any ideas?

**Comment by Lordubuntu94** [comment]
I think we may need a dedicated menu (reachable with a button) for chat settings, so even for future updates we can add there more features.
For the positioning I was thinking to add it specifically into the selected chats on top right.

Something like this (forgive me for my paint skills haha) : https://imgur.com/a/S0S44ls

As you can see i did 3 examples, classic 3 dots and hamburger icons and then a little message cloud (just to give you an idea xD)
On the bottom left, the chat settings with tick boxes for each feature.

Hope it was helpful, thanks as always!

**Comment by Lordubuntu94** [comment]
Another feature to add to the chat settings could be the "Hide offline contacts".
I think this one is very good/useful.

**Comment by ChristopherKlay** [comment]
Hiding the message preview is already working and added to the new settings menu.

Hiding "offline" contacts is a bit tricky. It's possible to hide them (with a tiny bit of flickering) but there is no way to filter if a contact that has it's online status hidden via privacy settings is actually online or offline.

Would simply removing only strictly "offline" people, leaving invisible ones as "online" be a solution?

**Comment by Lordubuntu94** [comment]
Just to better understand. You can actually force the online status to a contact that is actually invisible?
If that's the case(as far as cool it sound) i think it's not the way to go, because it would break the purpose of going invisible.

Could you force the offline status to the invisible, instead of the online and then procede to hide both real offline and invisible contacts?

**Comment by ChristopherKlay** [comment]
Haha, no i (sadly? :p) can't do that.

I meant that i could group invisible people with either "online/inactive/playing" or "offline" people, but they don't get grouped by default, because instead of actually showing as offline, they simply show up in the list without any online status at all.

I opted to select those with their own option.

**Comment by Lordubuntu94** [comment]
Hey Christopher, 
do you think it's possible (and not too hard) to make a notification system, using the notification's template stadia already has ?
Something like "player **x** has come online", "player **y** is playing Destiny 2"(without the popup sound ofc), similar to steam.
