### ISSUE TITLE
Stadia parameter to change display language

### ISSUE THREAD

**Issue by condorXI** [ChristopherKlay/StadiaEnhanced#22]
Hi,

thanks for this great Chrome extension!

Could you please think about supporting the Stadia URL parameter to change the display language.
Otherwise the current language set in google settings will be used in links.

Example: https://stadia.google.com/home?hl=en

**Comment by ChristopherKlay** [comment]
This should already be the case, if i understand you correctly.

I'm currently using "English" as the main language on my Google account, but using the hl value `de` results in both Stadia and the translation for Stadia Enhanced being in german. Keep in mind this only works if Stadia Enhanced supports the language set via the URL, if that's not the case it will default to english.

**Comment by condorXI** [comment]
For me its vice versa. I have my Google account set to German but Stadia with the URL parameter set to English. Now, when I use your extension I always get switched back to German, because the parameter is cut off at some point. I'll do some more tests about this.
Thanks!

**Comment by ChristopherKlay** [comment]
I think i found where the issue comes into play now.

The issue here isn't that the extension overwrites your selected language; it still uses the language Stadia uses at all times. The problem is most likely that shortcuts like the "Pro" one near the store page cuts off the parameter and Stadia reverts back to the language set on your account.

Could you test that?

**Comment by ChristopherKlay** [comment]
Found the issue and it will be solved in the upcoming `v1.6.0` patch (:

**Comment by condorXI** [comment]
Thanks! Its working
