### ISSUE TITLE
[Feature Request] quality of life improvements

### ISSUE THREAD

**Issue by Lordubuntu94** [ChristopherKlay/StadiaEnhanced#23]
Hey Christopher got some new ideas:

1) Add a new filter to show/hide the entire Screenshots section from the bottom of the home page.
    
    **Position**: update the "activate filter" in the drop down menu, you could make it similiar to the clock label. 
    If you click once you activate the game filter, if you click twice it will activate the hide screenshots section too.  

    **Reason**: I think some players prefer a cleaner home page, if they want to see screenshots, you already did a dedicated 
    button from the drop down menu.

2) Add a show/hide filter for screenshots like the one we have for game library.

    **Position**: same logic of point 1) .

    **Reason**: with the feature of hide specific screenshots every player will be able to create a more customized collection. 
    It will be something like a "homemade" preferred screenshots/clip section.

3) Add buttons for download/share/delete screenshot and clips.

    **Position**: on top right of the clip/screenshot preview, like you did for the eye icon to hide games from the library.
    
    **Reason**: there's little to say. This is really a quality of life change. As it is now, if you want to eliminate or share a 
    screenshot, you are forced to scroll down, find the screen, open it, click the delete button, click "agree" into the popup to 
    confirm the delete. So many things to just delete 1 screenshot.

4) (I admit this one may be impossible to do for browsers limitations) Add the possibility to start stadia.com in fullscreen.
    Like a script that auto F11 when i open stadia.

    **Reason**: personally, i hate the top bar of the browser. The home page in fullscreen is way better/clean looking. But clicking 
    everytime F11 is annoying.

So, that's it for now, let me know what you think! And as always, thank you for reading.

**Comment by ChristopherKlay** [comment]
Looking at all your great feature suggestions; How about a new settings menu in general?

I was thinking about changing the dropdown menu into a full page settings menu (similar to when you enter Stadias own settings) and then categorize for general settings, stream settings, chat and so on. That way around the user has one place with all the "enhancements" to set.

How does that sound?

**Comment by Lordubuntu94** [comment]
It's a perfect idea!

**Comment by Lordubuntu94** [comment]
Hey! Got a new idea (this one could be good) : 

- Add a new page "Community" able to display this web page : 
  https://community.stadia.com/t5/Community/ct-p/en_community
  
  **Position**: home page, specifically near "Pro".

  **Reason**: I think this is something google should've added from day 1, I mean it's the stadia forum. And having it just a click 
  away i think it could benift everyone.

Another thought to share regarding this feature: this "community" page could also not be limited only to the stadia forum, maybe it could have also some links to main socials like reddit/twitter/facebook/youtube. Of course the more stuff we put in the harder it will get to make, i don't know. The main goal is to make the platform more social, easier to share thoughts, gaming experiences and news without the loading of 4 different web pages xD

Let me know what you think!

**Comment by ChristopherKlay** [comment]
Currently going through the ideas and adding them to the extension where i can.

- Add a new filter to show/hide the entire Screenshots section from the bottom of the home page.

Already done and added as a option in the new settings menu.

- Add a show/hide filter for screenshots like the one we have for game library.

This should be doable due to the data id of screenshots/videos, but has a lower priority for me right now. It will come down the line in case Google doesn't update their functionality further however.

- Add buttons for download/share/delete screenshot and clips.

This one is a bit tricky. Share/Delete won't be easy to do (if doable at all) due to Stadias JS backend handling them. It's very easy to add a "Share" button that copies the share URL for the specific media entry, but those URLs won't work because the media entry isn't "shared" until you actually hit "Share" in the full preview. Otherwise it just gives a "Unavailable or not shared" error when using the link. Downloading is definitely possible since the URL is available in a easy format (the preview and the full image just have a different parameter at the end of the file path) but Google has pretty frequently changed things about them. I will need to check if i can add a download button, without it breaking by patches easily over time.

- (I admit this one may be impossible to do for browsers limitations) Add the possibility to start stadia.com in fullscreen.
Like a script that auto F11 when i open stadia.

This is (afaik) indeed not possible due to browser limitations (or better said sandbox limitations of JS and such). We can fullscreen a element (like a video) but it's not possible to trigger F11 via JS for example.

- Add a new page "Community" able to display this web page

While it's definitely possible to link it, it won't be possible to "load it" into the actual Stadia page (i.e. the space below the top bar for example). There will be cross-origin issues, even when using not exactly "smooth" solutions, like iframes. I am however definitely adding it to the "Shortcuts" section of the new menu.

**Comment by LeMeD** [comment]
Hi  @ChristopherKlay 

To begin, let me thank you for your great extension, as Stadia player, it is very useful ! I'm am learning code for non-professional purpose, I'm actually try to learn JS.

Could you please let me try to make a PR to add the "Community Link" ? It looks like a beginner-friendly feature to be developed.

Thank you in advance for your answer :)

**Comment by ChristopherKlay** [comment]
Hey @LeMeD (:

I actually already made a lot of changes behind the scenes (GitHub is only updated on new versions, not live) and a "Community" link is part of the new shortcuts category that will drop with `v1.6.0` hopefully soon (if Stadia could just stop making changes 😄).

Loading it directly into the Stadia content page sadly isn't possible due to cross-origin restrictions.

**Comment by Lordubuntu94** [comment]
Hey Chris, i got another idea (i think you'll like this one).

When you became a pro member, if a specific game you want to buy it's flagged as "pro", normally you are unable to buy it. You are forced to wait the expiration date of pro.

What I ask is to have displayed the button to buy the "flagged" game for pro players too.

Let me know what you think 😄

**Comment by ChristopherKlay** [comment]
I don't think this is actually possible right now; even tho i would love to implement it.

The issue is, Stadia afaik doesn't just "hide" the button, it uses the same button you usually click on to buy the game, to start the game if you already own it or claimed it. If you inspect the button itself you can even see that the element for the price just get's hidden and the "Buy" gets replaced with "Play". The button also isn't a link or something i could change easily, it just acts as a trigger.
