### ISSUE TITLE
[Feature Request] Add a sponsor links / section 

### ISSUE THREAD

**Issue by mlostekk** [ChristopherKlay/StadiaEnhanced#26]
Great work, thanks for enriching the Stadia experience. But to honor this even more please setup a sponsor section / link with a paypal moneypool for example. 

Keep up the great work

(_I am the dev of cloudy, Stadia on iOS and had great experience with moneypools/patreon/discord. I saw you did the translation in german? Dann ab mit dir in unseren cloudy discord und schreib mich direkt an. Link findest du hier https://github.com/mlostekk/Cloudy_)

**Comment by ChristopherKlay** [comment]
I'm currently using [BuyMeACoffee](https://www.buymeacoffee.com/christopherklay), which is linked via the coffee cup, if you click the extension icon - it's just not linked directly on the Stadia page.

However, people did ask me to be able to use PayPal directly a few times already, so a moneypool might be a good option. I kinda feel like Patreon and the whole "Pay me monthly to see a preview of upcoming patches" (as an example) doesn't exactly fit this project, since i don't want to push exclusivity onto something that everyone should be able to fully enjoy.

Ich meld mich die Tage bei dir, sobald ich ein wenig Zeit habe; Wochenende ist irgendwie noch nicht bei mir angekommen 😄

**Comment by mlostekk** [comment]
Okay, thats also a good option!

Easy, bis später
