### ISSUE TITLE
[Feature request] Add resolutions infos for each game page in the store 

### ISSUE THREAD

**Issue by Lordubuntu94** [ChristopherKlay/StadiaEnhanced#31]
For example, I go to the division 2 store page.
Near youtube and metacritic buttons you can add a label "Supported resolutions : 1080p 60fps / 4k 60fps"

For this task https://stadiahead.com/games might be handy

**Comment by ChristopherKlay** [comment]
The issue with both these great suggestions is that they rely on data that isn't actually available through Stadia, which creates a couple of issues.

- The data isn't actually verified in most cases. We've had cases where people thought the resolution of a game is 1440p (on 4K) for multiple weeks, just to get a confirmation that it's upscaled 1080p.
- The data isn't actually known for a lot of games.
- The data needs to be updated manually. Which means it's further delayed by updates to the extension (on top of the delay introduced by having to find out the resolution/fps in the first place).

In the end, a list of games and their resolution/fps (or better said "available data", since a lot is guessed/unknown) wouldn't be hard to add to Stadia Enhanced; Making fps filtering and such work consistently however definitely would be, because said list wouldn't be able to make sure that a lot of games (and all new ones) are actually 60fps at a specific resolution.

The suggestion is actually already on my to-do list, due to #25 which is effectively the same functionality. It just needs to wait until i can figure out a sustainable and reliable path for it.
