### ISSUE TITLE
Version 1.7 prevent 4K options

### ISSUE THREAD

**Issue by chengB12** [ChristopherKlay/StadiaEnhanced#35]
chrome version: 87.0.4280.88
extension version: 1.7.0

after enable stadia enhanced, I can't enable 4k options in stadia performance setting:

![image](https://user-images.githubusercontent.com/66152032/101417399-827bb400-38a0-11eb-945c-e8775d4dcc73.png)

whenever I turn on 4k option:
![image](https://user-images.githubusercontent.com/66152032/101417477-9aebce80-38a0-11eb-9991-3da4c119c615.png)

after reload page, it will switch back to 1080p.

Turning of stadia enhanced extension will make 4k option stay

**Comment by chengB12** [comment]
If I change extension settings to force vp9 and 4k, stadia can stream at 4k.

However, for setting: default, it prevent stadia goes to 4k

**Comment by ChristopherKlay** [comment]
This is.. weird, to say the least.

Getting switched back to 1080p should only happen, if 4K isn't supported by your device. In fact, all Stadia Enhanced does is remove the element attributes of the 4K option that blocks you from clicking it - it doesn't "set" the option for you at all.

If your device doesn't support 4K, you can select 4K with Stadia Enhanced and while it will default back to showing you 1080p in the settings if you refresh the page, 4K will still be enabled. That's just a visual bug.

If your device supports 4K however, it shouldn't reset to 1080p at all.

Could you do me a favour and open Stadia, then hit Ctrl+Shift+I, go to "console" and paste this in;

`localStorage.getItem("enhanced_DeskWidth") + "x" + localStorage.getItem("enhanced_DeskHeight") + " | " + screen.availWidth + "x" + screen.availHeight;`

and post the resolutions it shows here?

**Comment by chengB12** [comment]
On stadia home, it shows: "2560x1440 | 2560x1440"

**Comment by chengB12** [comment]
And it seems not just visual bug, since stadia reported that my device is not supported 4K while enhanced with default enabled

also, enhance did report stream quality is 1080 when playing in this case

**Comment by ChristopherKlay** [comment]
Okay, this is weird. Your resolution is actually 1440p, not 2160p (4K) and Stadia as far as i know doesn't support streaming 4K to a 2K monitor to begin with - which means without Stadia Enhanced, the stream should only reach 1440p (2560x1440px) to begin with.

It looks like the bug here is that "default" in your case defaults to a 1080p stream instead of a 1440p one and i'll look into that.

Selecting 4K in the Stadia settings (it will show 1080p if you refresh, but 4K will be selected) and switching the resolution in the Stadia Enhanced menu to 1440p (your monitor resolution) or 2160p (4K) should deliver a 1440p/2160p stream as well.

**Comment by chengB12** [comment]
My monitor is 4K, and I believe console return 2560 * 1440 because current viewport is less than 4K,
since it need remove browser title, scrollbars, ribbon/toolbars, and for windows, bottom task bars

**Comment by ChristopherKlay** [comment]
The value above (`screen.availWidth`) actually returns how much available width your browser has - which means it would be a very, very weird coincidence that you end up with exactly a different number, that's specifically tied to a different resolution (2K).

I used screen.availWidth because Stadia checks for the available size first when checking what resolutions are supported.

If you throw console.log(screen.width + "x" + screen.height); into the console however, to get the full screen size ignoring those factors, is the result actually 3840x2160 - which would be 4K?

**Comment by chengB12** [comment]
I don't know what exactly causing it, it seems have no issue with chrome 86/enhance 1.6

I don't know which upgrade would break it

**Comment by chengB12** [comment]
disable enhance, stadia again can stream 4K (using stream monitor to check resolution)

**Comment by chengB12** [comment]
update: I found v 1.7.1 fix it
