### ISSUE TITLE
"On Sale" link goes to wrong page

### ISSUE THREAD

**Issue by jacobgelling** [ChristopherKlay/StadiaEnhanced#38]
Clicking the "On Sale" link that Stadia Enhanced adds to the menu bar takes me to https://stadia.google.com/store/list/35 but it should take me to https://stadia.google.com/store/list/14, the current sale list.

![Screenshot 2020-12-12 at 17 19 08](https://user-images.githubusercontent.com/3254275/101989105-64e28c00-3c9e-11eb-8b0b-cf4309a1cf10.png)

**Comment by ChristopherKlay** [comment]
This was actually done because Google kept changing the list they actually use for sales.

They first used the "Current Deals" category, then they stopped updating it entirely (i.e. it had only two full price games in it) and started using the "Feature deals" section. Now they use the "On Sale" one again they started with. It's a bit of a completely unnecessary process.

I'll push `v1.7.3` fixing this in a minute.
