### ISSUE TITLE
Possible to make the site work on mobile.

### ISSUE THREAD

**Issue by Plnda** [ChristopherKlay/StadiaEnhanced#5]
Currently, on Android/iOS we need to request the desktop site on mobile to get stadia working. but the site doesn't scale that well on mobile. Is it possible that you can achieve a working mobile look?

**Comment by ChristopherKlay** [comment]
I'll look into it.

Most likely won't be do-able to allow for a mobile version, but a user friendly / scaled desktop view should be do-able. (:

**Comment by Plnda** [comment]
That would be awesome I'm working on a dedicated streaming iOS app for stadia. (got it working 🥳 ) But the UI looks horrible, especially since for some reason it wants to be 1200px for some elements. I would like with your permission use some of your js enhancements to make it into the iOS app.

**Comment by ChristopherKlay** [comment]
I looked into it and unfortunately rendering it correctly on a mobile device and/or below 1200px width would require a not exactly small amount of work, since the entire page is only supporting 720p and above desktop usage, which features a width of 1280px.

There's basically two ways to do this;

1. Scale the content to fit all elements, which would be usable but insanely user unfriendly, due to some elements being displayed way too small.
2. Pretty much write your own media query that adjusts pretty much the entire main content. This would provide a clean result, but would also require a ton of testing/adjustments until its done.

Both of those aren't solutions i would add to Stadia Enhanced right now, due to them also possibly breaking entirely if the site gets updated just slightly and mobile via chrome being unsupported in the first place.

> I would like with your permission use some of your js enhancements to make it into the iOS app.

Stadia Enhanced is designed to be build by and be shared by users and you can freely use it (or parts of it) in your app, as long as you follow the licence it's release under, effectively meaning the result is also freely available and the source openly available.
