### ISSUE TITLE
Force h264 on android phones and tablets?

### ISSUE THREAD

**Issue by awwe** [ChristopherKlay/StadiaEnhanced#77]
Would really love someone to do a chromium apk with forced h264 for Android. It would open up Stadia for many phones and tablets other than Qualcomm/Exynos. 

Would it be feasible? Posting it here because this extension is the one you can force h264 on Stadia

**Comment by ChristopherKlay** [comment]
Forcing h264 in general is a bit tricky, because if Stadia detects issues during start-up, it sometimes tries to switch to VP9 even if h264 is selected / "forced".

H264 should work fine on desktop by now and *should* work on Android via a browser allowing extensions as well, but that's really more a "if it works, it works" area, since bug-fixing for all possible combinations in that case would be a nightmare.

Modding the APK would most likely be possible, but at the same time immediately pushes you from that "Googles tolerates it" to "Google might as well just straight up restrict your account" area.

**Comment by awwe** [comment]
Thanks
