### ISSUE TITLE
Incorrect native resolution

### ISSUE THREAD

**Issue by flipcooke** [ChristopherKlay/StadiaEnhanced#98]
Using Lenovo Duet Chromebook. 

It has a native screen resolution of 1080p.

But it keeps defaulting to 720p. You have 2k and 4k as options, but why is 1080p is missing as an option?

**Comment by ChristopherKlay** [comment]
Due to 1080p and 720p not being "forceable" in the same way.

When you force 2K/4K you select "Up to 4K" in the settings and it will automatically stream in 1080p up to 1440p/2160p based on the available screen (which is what Enhanced is "faking").

Setting the same values for 720p/1080p however, is known to create a lot of issues. Stadia sometimes for examples locks into 720p when selecting 720p/1080p, or blocks the user from using anything above 1080p afterwards, until you manually adjust the Stadia settings again, despite the screen natively offering a higher resolution.

If you select "Native", the extension also doesn't actually affect your streams resolution - it will most likely default to 720p without Enhanced as well, if it does with Enhanced set to "Native". In most cases (especially with Chromebooks) there's simply an issue with the connection itself - in which case Stadia defaults to a lower resolution to try and avoid bandwidth/decoding issues.

**Comment by flipcooke** [comment]
Hi Christopher

Thanks for taking the time to explain ( and your support with this
extension), it is much appreciated
